check

diff --git a/.github/workflows/deploy.yaml b/.github/workflows/deploy.yaml
--- a/.github/workflows/deploy.yaml
+++ b/.github/workflows/deploy.yaml
@@ -1,12 +1,12 @@
 name: Deploy App
 
 on:
-  workflow_dispatch:
-    inputs:
-      tag:
-        description: 'Tag to deploy'
-        required: true
-
+  # workflow_dispatch:
+  #   inputs:
+  #     tag:
+  #       description: 'Tag to deploy'
+  #       required: true
+  [ push ]
 jobs:
   deploy:
     runs-on: ubuntu-latest
@@ -21,13 +21,13 @@ jobs:
         uses: actions/checkout@v2
         with:
           ref: ${{ github.event.inputs.tag }}
-      - name: Check if tag exists
-        run: |
-          git fetch --all --tags
-          if ! git tag | grep -q "^${{ github.event.inputs.tag }}$"; then
-            echo "error: Tag '${{ github.event.inputs.tag }}' not found"
-            exit 1
-          fi
+      # - name: Check if tag exists
+      #   run: |
+      #     git fetch --all --tags
+      #     if ! git tag | grep -q "^${{ github.event.inputs.tag }}$"; then
+      #       echo "error: Tag '${{ github.event.inputs.tag }}' not found"
+      #       exit 1
+      #     fi
       - name: Set up Go
         uses: actions/setup-go@v2
         with:
